# This example assume that you have:
# 1. A secret with your supersense configuration (see README)
# 2. An ingress controller (could be traefik)
# 3. Certmanager service available in your cluster


config:
  secretRef: osd-socialwall-secret

service:
  type: ClusterIP
  port: 8080
  
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: osd-socialwall.dev.minsky.cc
      paths:
        - "/"
  tls:
    - secretName: osd-socialwall.dev.minsky.cc-cert
      hosts:
        - osd-socialwall.dev.minsky.cc

# create secret
# $ kubectl create secret generic osd-socialwall-secret --from-env-file=.env

# to install only runs:
# $ helm install <your-realease-name> minsky/supersense -f values.yaml
